#!/usr/bin/env fish

# ==== Monitors ==== #

# TODO: use `hostname` to conditionally configure?
bspc monitor DVI-D-0 0 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 0 1 2 3 4 5 6 7 8 9

# ==== Configuration ==== #

# TODO: explain these

bspc config border_width 2
bspc config window_gap 10
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config split_ratio 0.50
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4

# ==== Colors ==== #
