#!/usr/bin/env fish

# ==== Monitors ==== #

# TODO: use `hostname` to conditionally configure?
# Use `xrandr` to get monitor name.
bspc monitor DVI-D-0 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

# ==== Config ==== #

# See `man bspwm`

bspc config border_width 2
bspc config window_gap 7
bspc config split_ratio 0.50
#bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config history_aware_focus true
bspc config pointer_modifier mod4

# ==== Colors ==== #

bspc config normal_border_color '#444444'
bspc config focused_border_color '#af5f5f'
bspc config urgent_border_color '#bd2c40'

